workspace = { members = ["termui"] }
[package]
name = "verynoha"
version = "0.1.0"
edition = "2021"

[dependencies]
termui = { path = "termui" }
serde = { version = "*", features = ["derive"]}
serde_json = "*"
